/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  eloqkv: {
    'EloqKV 简介': ['introduction'],
    快速开始: ['install-from-binary', 'docker-deploy'],
    部署: [
      'quick-start',
      'quick-start-ha-local-storage',
      'quick-start-ha',
      'manage-cluster',
      'upgrade',
      'prerequisite',
    ],
    管理: [
      'monitor',
      'configuration',
      'eloqkv-proxy',
      'dump-tools',
      'failover',
    ],
    'Redis 兼容性': ['kvstore_compatibility', 'known-limit'],
    命令参考: [
      {
        type: 'category',
        label: '列表',
        items: [
          'list/BLMOVE',
          'list/BLMPOP',
          'list/BLPOP',
          'list/BRPOP',
          'list/BRPOPLPUSH',
          'list/LINDEX',
          'list/LINSERT',
          'list/LLEN',
          'list/LMOVE',
          'list/LMPOP',
          'list/LPOP',
          'list/LPOS',
          'list/LPUSH',
          'list/LPUSHX',
          'list/LRANGE',
          'list/LREM',
          'list/LSET',
          'list/LTRIM',
          'list/RPOP',
          'list/RPOPLPUSH',
          'list/RPUSH',
          'list/RPUSHX',
        ],
      },
      {
        type: 'category',
        label: '哈希',
        items: [
          'hash/HDEL',
          'hash/HEXISTS',
          'hash/HGET',
          'hash/HGETALL',
          'hash/HINCRBY',
          'hash/HINCRBYFLOAT',
          'hash/HKEYS',
          'hash/HLEN',
          'hash/HMGET',
          'hash/HSET',
          'hash/HSETNX',
          'hash/HSTRLEN',
          'hash/HVALS',
          'hash/HRANDFIELD',
          'hash/HSCAN',
          'hash/HMSET',
        ],
      },
      {
        type: 'category',
        label: '集合',
        items: [
          'set/SADD',
          'set/SCARD',
          'set/SDIFF',
          'set/SDIFFSTORE',
          'set/SINTER',
          'set/SINTERSTORE',
          'set/SISMEMBER',
          'set/SMEMBERS',
          'set/SMISMEMBER',
          'set/SMOVE',
          'set/SPOP',
          'set/SRANDMEMBER',
          'set/SREM',
          'set/SSCAN',
          'set/SUNION',
          'set/SUNIONSTORE',
        ],
      },
      {
        type: 'category',
        label: '有序集合',
        items: [
          'zset/ZADD',
          'zset/ZCARD',
          'zset/ZCOUNT',
          'zset/ZDIFF',
          'zset/ZDIFFSTORE',
          'zset/ZINCRBY',
          'zset/ZINTER',
          'zset/ZINTERCARD',
          'zset/ZINTERSTORE',
          'zset/ZLEXCOUNT',
          'zset/ZMPOP',
          'zset/ZMSCORE',
          'zset/ZPOPMAX',
          'zset/ZPOPMIN',
          'zset/ZRANDMEMBER',
          'zset/ZRANGE',
          'zset/ZRANGEBYLEX',
          'zset/ZRANGEBYSCORE',
          'zset/ZRANK',
          'zset/ZREM',
          'zset/ZREMRANGEBYLEX',
          'zset/ZREMRANGEBYRANK',
          'zset/ZREMRANGEBYSCORE',
          'zset/ZREVRANGE',
          'zset/ZREVRANGEBYLEX',
          'zset/ZREVRANGEBYSCORE',
          'zset/ZREVRANK',
          'zset/ZSCAN',
          'zset/ZSCORE',
          'zset/ZSCORE',
          'zset/ZUNIONSTORE',
        ],
      },
      {
        type: 'category',
        label: '字符串',
        items: [
          'string/APPEND',
          'string/DECR',
          'string/DECRBY',
          'string/GET',
          'string/GETRANGE',
          'string/GETSET',
          'string/INCR',
          'string/INCRBY',
          'string/INCRBYFLOAT',
          'string/MGET',
          'string/MSET',
          'string/MSETNX',
          'string/SET',
          'string/SETNX',
          'string/SETRANGE',
          'string/STRLEN',
          'string/SUBSTR',
        ],
      },
      {
        type: 'category',
        label: '位图',
        items: [
          'bitmap/BITCOUNT',
          'bitmap/BITFIELD',
          'bitmap/BITFIELD_RO',
          'bitmap/BITOP',
          'bitmap/BITPOS',
          'bitmap/GETBIT',
          'bitmap/SETBIT',
        ],
      },
      {
        type: 'category',
        label: '发布订阅',
        items: [
          'pubsub/PSUBSCRIBE',
          'pubsub/PUBLISH',
          'pubsub/PUBSUB',
          'pubsub/PUNSUBSCRIBE',
          'pubsub/SUBSCRIBE',
          'pubsub/UNSUBSCRIBE',
        ],
      },
      {
        type: 'category',
        label: '事务',
        items: [
          'transaction/DISCARD',
          'transaction/EXEC',
          'transaction/MULTI',
          'transaction/UNWATCH',
          'transaction/WATCH',
        ],
      },
      {
        type: 'category',
        label: '脚本',
        items: [
          'scripting/EVAL',
          'scripting/EVALSHA',
          'scripting/SCRIPTEXISTS',
          'scripting/SCRIPTFLUSH',
          'scripting/SCRIPTLOAD',
        ],
      },
      {
        type: 'category',
        label: '通用',
        items: [
          'generic/DEL',
          'generic/DUMP',
          'generic/EXISTS',
          'generic/KEYS',
          'generic/RESTORE',
          'generic/SCAN',
          'generic/SELECT',
          'generic/SORT',
          'generic/TYPE',
        ],
      },
    ],
  },
};
module.exports = sidebars;
