/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //monoredisSidebar: ['MonoRedis'],
  //monosqlSidebar: ['MonoSQL'],
  monographdb: {
    快速上手: [
      'preconfig',
      'quick-start',
      'cluster-deployment',
      'upgrade-guide',
      'basic-sql-operations',
    ],
    连接数据库: ['connect-to-monodb/connect-by-client'],
    数据查询: [
      'data-query/simple-query',
      'data-query/advance-query',
      'data-query/test-scheme-design',
    ],
    MySQL兼容性: ['mysql-compatibility', 'difference_with_mysql'],
    SQL参考: [
      'sql-reference/account-management/alter-user',
      'sql-reference/account-management/create-role',
      'sql-reference/account-management/create-user',
      'sql-reference/account-management/grant',
      'sql-reference/account-management/revoke',
      'sql-reference/data-manipulation/insert-and-load-data/load-data-infile',
      'sql-reference/data-manipulation/selecting-data/select-into-outfile',
      'sql-reference/data-manipulation/selecting-data/select-with-rollup',
    ],
  },

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
